### ISSUE TITLE
embedded data from HAL is not cached

### ISSUE THREAD

**Issue by manchuck** [badgateway/ketting#273] opened 2020-10-19 16:17 UTC
Given the following response from calling `https://my.api.com/customers`:

```json
{
  "limit": 100,
  "offset": null,
  "total_count": 2,
  "_links": {
    "self": {
      "href": "https://my.api.com/customers"
    }
  },
  "_embedded": {
    "my:customers": [
      {
        "customer_id": "1",
        "label": "Customer one",
        "_links": {
          "self": {
            "href": "https://my.api.com/customers/1"
          }
        }
      },
      {
        "customer_id": "2",
        "label": "Customer two",
        "_links": {
          "self": {
            "href": "https://my.api.com/customers/2"
          }
        }
      }
    ]
  }
}

```

```js

import {Client} from 'ketting';
const client = new Client('https://my.api.com);

const customerResource = client.go('/customers');

const state = await customerResource.get();
const customers = state.getEmbedded();
console.log({customers});

const stateTwo = await customerResource.get();
const customerAgain = state.getEmbedded();
console.log({customersAgain});
```

The `_embedded` is not cached therefore, the second call to `state.getEmbedded` will return an empty array for the embedded.

**Comment by evert** [comment] 2020-10-22 15:10
Hi @manchuck ,

This is by design. Ketting basically considers embedded items to be different resources entirely, and caches the embedded items separately.

To get access to the embedded items consistently, consider using `customerResource.followAll('my:customers'))`.

getEmbedded is not meant to be used directly like this.

This question pops up from time to time, so I do feel this is something that needs to be addressed/documented a bit better

**Comment by evert** [comment] 2020-11-06 05:07
Closing this as there has been no further feedback.

**Closed by evert** 2020-11-06 05:07 UTC

**Comment by manchuck** [comment] 2020-11-10 15:27
Sorry been crazy but yea if the documentation can be improved to reflect this change then I'm ok with that.

It would be nice if we can include our own caching adapter. This way we can define our own caching policies instead of wrapping ketting calls.  I'll check to see if that is a requested feature or not and create the request

**Comment by evert** [comment] 2020-11-10 16:50
@manchuck , you are able to create your own caching adapter. The current version ships with 3 strategies (forever, short, never), but custom ones are definitely possible.

Let me know if it works for you!
